console.log(typeof (undefined + 1)); // number 'NaN' 
console.log(typeof ('true' == true)); // bolean 'false'
console.log(typeof (false == 'false')) ;// bolean 'false'
console.log(typeof (null == '')); // bolean 'false'
console.log(typeof (3 ** (9 / 3))); // number '27' 
console.log(typeof (!!'false' == !!'true')); // bolean 'true' 
console.log(typeof (0 || '0' && 1)); // number '1'
console.log(typeof (1 < 2 < 3)); // bolean 'true'
console.log(typeof ('foo'+ + +'bar')); // string 'FooNan'
console.log(typeof (3 ** 2 / 3)); // number '3' 
console.log(typeof (1 < 2 > 3)); // bolean 'false'
console.log(typeof ((+null == false) < 1)); // bolean 'false'
console.log(typeof (false && true || true)); //  bolean 'true'
console.log(typeof (false && (true || true))); //bolean 'false'
console.log(typeof ((+null == false) < 1 ** 5)); // bolean 'false'
console.log()